version: "3.9"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5435:5432"
    expose:
      - "5435"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - rcrPostgresData:/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  rcrPostgresData:
    driver: local
