version: "3.9"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      target: release
    expose:
      - "3000"
      - "3001"
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - PORT=${PORT}
      - INTERNAL_PORT=${INTERNAL_PORT}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    command: bun run src/index.ts
