version: "3.9"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      target: release
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
    command: bun run src/index.ts
