replicaCount: 1

image:
  repository: docker.io/radixdlt/radix-connect-relay
  pullPolicy: Always
  tag: ""

docker:
  secret_name: docker.io/radixdlt

imagePullSecrets:
  - name: dockerhub

nameOverride: "radix-connect-relay"
fullnameOverride: "radix-connect-relay"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "radix-connect-relay"

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 1m
  hosts: []
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: metrics
readinessProbe:
  httpGet:
    path: /
    port: metrics

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

params: []

secrets: []

metrics:
  enabled: true
  port: 3001
