apiVersion: batch/v1
kind: CronJob
metadata:
  name: delete-old-requests
  labels:
    {{- include "radix-connect-relay.labels" . | nindent 4 }}
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: delete-old-requests
            image: docker.io/library/postgres:15
            env:
            {{- range $key, $value := .Values.params }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $secret := .Values.secrets }}
            - name: {{ $secret.env_variable }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secret.external_secret_name }}
                  key: {{ $secret.secret_key }}
            {{- end }}
            command: ["/bin/sh", "-c"]
            args:
              - |
                psql $DATABASE_URL -c "DELETE FROM Request WHERE createdAt < NOW() - INTERVAL '5 minutes';"
          restartPolicy: OnFailure

